apiVersion: apps/v1
kind: Deployment
metadata:
  name: health
  namespace: app
spec:
  selector:
    matchLabels:
      app: health
  template:
    metadata:
      labels:
        app: health
    spec:
      containers:
        - name: health
          image: ko://github.com/izaakdale/health-server
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: health
  namespace: app
spec:
  selector:
    app: health
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: health
  namespace: app
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: PathPrefix(`/_/health`)
      services:
        - kind: Service
          name: health
          namespace: app
          port: 80
      middlewares:
        - name: striphealthprefix
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: striphealthprefix
  namespace: app
spec:
  stripPrefix:
    prefixes:
      - /_/health
---

